SELECT * FROM ADDRESS;
SELECT * FROM CLASSES;
SELECT * FROM PARENTS;
SELECT * FROM SCHOOL;
SELECT * FROM STAFF;
SELECT * FROM STAFF_SALARY;
SELECT * FROM STUDENT_CLASSES;
SELECT * FROM STUDENT_PARENT;
SELECT * FROM STUDENTS;
SELECT * FROM SUBJECTS;

-- FETCH THE STUDENT FIRST NAME AND THEIR CLASS 

SELECT S.ID, S.FIRST_NAME, SC.CLASS_ID
FROM STUDENT_CLASSES SC
JOIN STUDENTS S ON SC.STUDENT_ID = S.ID;

-- FETCH ALL THE STAFF DETAILS AND SALARY (PRIORITY IS SET ON THE FIRST TABLE)

SELECT S.STAFF_ID, S.FIRST_NAME, SS.SALARY, SS.CURRENCY
FROM STAFF S
LEFT JOIN STAFF_SALARY SS ON S.STAFF_ID = SS.STAFF_ID;


-- FETCH ALL THE STAFF NAME, SALARY DETAILS AND THE CLASSES TAKING

SELECT S.STAFF_ID, S.FIRST_NAME, S.LAST_NAME, SS.SALARY, SS.CURRENCY, CL.SUBJECT_ID
FROM STAFF S
LEFT JOIN STAFF_SALARY SS ON S.STAFF_ID = SS.STAFF_ID 
LEFT JOIN CLASSES CL ON CL.TEACHER_ID= S.STAFF_ID;
 

-- Full join return (Inner Join + Left join + Right join)
SELECT S.STAFF_ID, S.FIRST_NAME, S.LAST_NAME, CL.SUBJECT_ID
FROM STAFF S
FULL JOIN CLASSES CL ON CL.TEACHER_ID= S.STAFF_ID;

SELECT S.STAFF_ID, S.FIRST_NAME, S.LAST_NAME, SS.SALARY, SS.CURRENCY, CL.SUBJECT_ID
FROM STAFF S
LEFT JOIN STAFF_SALARY SS ON S.STAFF_ID = SS.STAFF_ID 
FULL JOIN CLASSES CL ON CL.TEACHER_ID= S.STAFF_ID;


-- TO GET THE ADDRESS STAFF AND THE PARENT
SELECT P.FIRST_NAME AS P_FIRST_NAME, P.lAST_NAME AS P_LAST_NAME, 
P.GENDER AS P_GENDER, S.FIRST_NAME AS S_FIRST_NAME, S.LAST_NAME AS S_LAST_NAME, A.STREET, A.CITY, A.STATE
FROM ADDRESS A
FULL JOIN PARENTS P ON A.ADDRESS_ID = P.ADDRESS_ID
FULL JOIN STAFF S ON A.ADDRESS_ID = S.ADDRESS_ID;



-- CROSS JOIN (RETURN CARTESIAN PRODUCT)
SELECT SC.SCHOOL_NAME, SC.EDUCATION_BOARD, S.STAFF_TYPE, S.FIRST_NAME, S.LAST_NAME
FROM SCHOOL SC
CROSS JOIN STAFF S

-- NATURAL JOIN (IT WILL RETURN AN INNER JOIN IF THERE ARE COLUMN SHARING THE SAME NAME IF NOT IT RETURN CROSS JOIN)
SELECT S.ID, S.FIRST_NAME, SC.CLASS_ID
FROM STUDENT_CLASSES SC
NATURAL JOIN STUDENTS S ;




---- CREAT A NEW TABLE 
CREATE TABLE CHILD
(
	ID               VARCHAR(20) PRIMARY KEY
  , FIRST_NAME       VARCHAR(100) NOT NULL
  , LAST_NAME        VARCHAR(100) NOT NULL
  , GENDER           VARCHAR(10) CHECK (GENDER IN ('M', 'F', 'Male', 'Female'))
  , AGE              INT
  , DOB              DATE
  , CHILD_PARENT 	 VARCHAR(100) NOT NULL
);

INSERT INTO CHILD VALUES
        ('STD10001','Lindy','O''Connell','Male',6,TO_DATE('2014-01-13', 'YYYY-MM-DD'),'STD10002'),
        ('STD10002','Madison','Walder','Male',6,TO_DATE('2014-01-19', 'YYYY-MM-DD'),'STD10004'),
        ('STD10003','Marve','Sheaber','Male',6,TO_DATE('2014-03-11', 'YYYY-MM-DD'),'STD10001'),
        ('STD10004','Jesselyn','Greaterex','Female',6,TO_DATE('2014-03-31', 'YYYY-MM-DD'),'STD10005'),
        ('STD10005','Leigh','Kipling','Male',6,TO_DATE('2014-02-02', 'YYYY-MM-DD'),'STD10003');
		
SELECT * FROM CHILD;

-- SELF JOIN (JOIN TABLEW TO ITSELFT)
SELECT CH.FIRST_NAME, CH.LAST_NAME, PARENT.CHILD_PARENT AS PARENT_ID
FROM CHILD AS CH
JOIN CHILD AS PARENT ON CH.ID = PARENT.CHILD_PARENT;

