SELECT * FROM ADDRESS;
SELECT * FROM CLASSES;
SELECT * FROM PARENTS;
SELECT * FROM SCHOOL;
SELECT * FROM STAFF;
SELECT * FROM STAFF_SALARY;
SELECT * FROM STUDENT_CLASSES;
SELECT * FROM STUDENT_PARENT;
SELECT * FROM STUDENTS;
SELECT * FROM SUBJECTS;

-- FETCH THE STUDENT FIRST NAME AND THEIR CLASS 

SELECT S.ID, S.FIRST_NAME, SC.CLASS_ID
FROM STUDENT_CLASSES SC
JOIN STUDENTS S ON SC.STUDENT_ID = S.ID;

-- FETCH ALL THE STAFF DETAILS AND SALARY (PRIORITY IS SET ON THE FIRST TABLE)

SELECT S.STAFF_ID, S.FIRST_NAME, SS.SALARY, SS.CURRENCY
FROM STAFF S
LEFT JOIN STAFF_SALARY SS ON S.STAFF_ID = SS.STAFF_ID;


-- FETCH ALL THE STAFF NAME, SALARY DETAILS AND THE CLASSES TAKING

SELECT S.STAFF_ID, S.FIRST_NAME, S.LAST_NAME, SS.SALARY, SS.CURRENCY, CL.SUBJECT_ID
FROM STAFF S
LEFT JOIN STAFF_SALARY SS ON S.STAFF_ID = SS.STAFF_ID 
LEFT JOIN CLASSES CL ON CL.TEACHER_ID= S.STAFF_ID;
